// flow-typed signature: 9e1fcf3f353a7bda939fec1ce1161264
// flow-typed version: <<STUB>>/dom.position_v0.0.0/flow_v0.58.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'dom.position'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'dom.position' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'dom.position/index' {
  declare module.exports: $Exports<'dom.position'>;
}
declare module 'dom.position/index.js' {
  declare module.exports: $Exports<'dom.position'>;
}
